# Base Image
FROM nginx:alpine

# Copy project anf files
COPY index.html /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/nginx.conf

# Expose port where you want to access application.
EXPOSE 80

